c-library allegro
    \c #include <allegro5/allegro.h>
    \c #include <allegro5/allegro_acodec.h>
    \c #include <allegro5/allegro_color.h>
    \c #include <allegro5/allegro_font.h>
    \c #include <allegro5/allegro_ttf.h>
    \c #include <allegro5/allegro_image.h>
    \c #include <allegro5/allegro_primitives.h>
    \c bool gforth_al_init(){ return al_init();}
    
    s" allegro"            add-lib
    s" allegro_audio"      add-lib
    s" allegro_acodec"     add-lib
    s" allegro_image"      add-lib
    s" allegro_primitives" add-lib
    s" allegro_font"       add-lib
    s" allegro_ttf"        add-lib
    c-function al_init gforth_al_init -- n
    include afkit/dep/allegro5/allegro-gforth.f
end-c-library

\ Aren't emacs keyboard macros great?
' ALLEGRO_TIMEOUT alias /ALLEGRO_TIMEOUT
' ALLEGRO_COLOR alias /ALLEGRO_COLOR
' _al_tagbstring alias /_al_tagbstring
' ALLEGRO_FILE_INTERFACE alias /ALLEGRO_FILE_INTERFACE
' ALLEGRO_LOCKED_REGION alias /ALLEGRO_LOCKED_REGION
' ALLEGRO_EVENT_SOURCE alias /ALLEGRO_EVENT_SOURCE
' ALLEGRO_ANY_EVENT alias /ALLEGRO_ANY_EVENT
' ALLEGRO_DISPLAY_EVENT alias /ALLEGRO_DISPLAY_EVENT
' ALLEGRO_JOYSTICK_EVENT alias /ALLEGRO_JOYSTICK_EVENT
' ALLEGRO_KEYBOARD_EVENT alias /ALLEGRO_KEYBOARD_EVENT
' ALLEGRO_MOUSE_EVENT alias /ALLEGRO_MOUSE_EVENT
' ALLEGRO_TIMER_EVENT alias /ALLEGRO_TIMER_EVENT
' ALLEGRO_TOUCH_EVENT alias /ALLEGRO_TOUCH_EVENT
' ALLEGRO_USER_EVENT alias /ALLEGRO_USER_EVENT
' ALLEGRO_EVENT alias /ALLEGRO_EVENT
' ALLEGRO_FS_ENTRY alias /ALLEGRO_FS_ENTRY
' ALLEGRO_FS_INTERFACE alias /ALLEGRO_FS_INTERFACE
' ALLEGRO_DISPLAY_MODE alias /ALLEGRO_DISPLAY_MODE
' ALLEGRO_JOYSTICK_STATE alias /ALLEGRO_JOYSTICK_STATE
' ALLEGRO_JOYSTICK_STATE_stick alias /ALLEGRO_JOYSTICK_STATE_stick
' ALLEGRO_KEYBOARD_STATE alias /ALLEGRO_KEYBOARD_STATE
' ALLEGRO_MOUSE_STATE alias /ALLEGRO_MOUSE_STATE
' ALLEGRO_TOUCH_STATE alias /ALLEGRO_TOUCH_STATE
' ALLEGRO_TOUCH_INPUT_STATE alias /ALLEGRO_TOUCH_INPUT_STATE
' ALLEGRO_MEMORY_INTERFACE alias /ALLEGRO_MEMORY_INTERFACE
' ALLEGRO_MONITOR_INFO alias /ALLEGRO_MONITOR_INFO
' ALLEGRO_TRANSFORM alias /ALLEGRO_TRANSFORM
' ALLEGRO_STATE alias /ALLEGRO_STATE
' ALLEGRO_SAMPLE_ID alias /ALLEGRO_SAMPLE_ID
' ALLEGRO_VERTEX_ELEMENT alias /ALLEGRO_VERTEX_ELEMENT
' ALLEGRO_VERTEX alias /ALLEGRO_VERTEX

\ rename struct fields. Keyboard macros again!
' ALLEGRO_TIMEOUT-__pad1__ alias ALLEGRO_TIMEOUT.__pad1__
' ALLEGRO_TIMEOUT-__pad2__ alias ALLEGRO_TIMEOUT.__pad2__
' ALLEGRO_COLOR-b alias ALLEGRO_COLOR.b
' ALLEGRO_COLOR-r alias ALLEGRO_COLOR.r
' ALLEGRO_COLOR-g alias ALLEGRO_COLOR.g
' ALLEGRO_COLOR-a alias ALLEGRO_COLOR.a
' _al_tagbstring-data alias _al_tagbstring.data
' _al_tagbstring-slen alias _al_tagbstring.slen
' _al_tagbstring-mlen alias _al_tagbstring.mlen
' ALLEGRO_FILE_INTERFACE-fi_ferror alias ALLEGRO_FILE_INTERFACE.fi_ferror
' ALLEGRO_FILE_INTERFACE-fi_fungetc alias ALLEGRO_FILE_INTERFACE.fi_fungetc
' ALLEGRO_FILE_INTERFACE-fi_fopen alias ALLEGRO_FILE_INTERFACE.fi_fopen
' ALLEGRO_FILE_INTERFACE-fi_fseek alias ALLEGRO_FILE_INTERFACE.fi_fseek
' ALLEGRO_FILE_INTERFACE-fi_fflush alias ALLEGRO_FILE_INTERFACE.fi_fflush
' ALLEGRO_FILE_INTERFACE-fi_feof alias ALLEGRO_FILE_INTERFACE.fi_feof
' ALLEGRO_FILE_INTERFACE-fi_fclose alias ALLEGRO_FILE_INTERFACE.fi_fclose
' ALLEGRO_FILE_INTERFACE-fi_ftell alias ALLEGRO_FILE_INTERFACE.fi_ftell
' ALLEGRO_FILE_INTERFACE-fi_ferrmsg alias ALLEGRO_FILE_INTERFACE.fi_ferrmsg
' ALLEGRO_FILE_INTERFACE-fi_fclearerr alias ALLEGRO_FILE_INTERFACE.fi_fclearerr
' ALLEGRO_FILE_INTERFACE-fi_fsize alias ALLEGRO_FILE_INTERFACE.fi_fsize
' ALLEGRO_FILE_INTERFACE-fi_fwrite alias ALLEGRO_FILE_INTERFACE.fi_fwrite
' ALLEGRO_FILE_INTERFACE-fi_fread alias ALLEGRO_FILE_INTERFACE.fi_fread
' ALLEGRO_LOCKED_REGION-data alias ALLEGRO_LOCKED_REGION.data
' ALLEGRO_LOCKED_REGION-pixel_size alias ALLEGRO_LOCKED_REGION.pixel_size
' ALLEGRO_LOCKED_REGION-pitch alias ALLEGRO_LOCKED_REGION.pitch
' ALLEGRO_LOCKED_REGION-format alias ALLEGRO_LOCKED_REGION.format
' ALLEGRO_EVENT_SOURCE-__pad alias ALLEGRO_EVENT_SOURCE.__pad
' ALLEGRO_ANY_EVENT-source alias ALLEGRO_ANY_EVENT.source
' ALLEGRO_ANY_EVENT-type alias ALLEGRO_ANY_EVENT.type
' ALLEGRO_ANY_EVENT-timestamp alias ALLEGRO_ANY_EVENT.timestamp
' ALLEGRO_DISPLAY_EVENT-orientation alias ALLEGRO_DISPLAY_EVENT.orientation
' ALLEGRO_DISPLAY_EVENT-x alias ALLEGRO_DISPLAY_EVENT.x
' ALLEGRO_DISPLAY_EVENT-source alias ALLEGRO_DISPLAY_EVENT.source
' ALLEGRO_DISPLAY_EVENT-y alias ALLEGRO_DISPLAY_EVENT.y
' ALLEGRO_DISPLAY_EVENT-type alias ALLEGRO_DISPLAY_EVENT.type
' ALLEGRO_DISPLAY_EVENT-height alias ALLEGRO_DISPLAY_EVENT.height
' ALLEGRO_DISPLAY_EVENT-timestamp alias ALLEGRO_DISPLAY_EVENT.timestamp
' ALLEGRO_DISPLAY_EVENT-width alias ALLEGRO_DISPLAY_EVENT.width
' ALLEGRO_JOYSTICK_EVENT-stick alias ALLEGRO_JOYSTICK_EVENT.stick
' ALLEGRO_JOYSTICK_EVENT-source alias ALLEGRO_JOYSTICK_EVENT.source
' ALLEGRO_JOYSTICK_EVENT-id alias ALLEGRO_JOYSTICK_EVENT.id
' ALLEGRO_JOYSTICK_EVENT-button alias ALLEGRO_JOYSTICK_EVENT.button
' ALLEGRO_JOYSTICK_EVENT-type alias ALLEGRO_JOYSTICK_EVENT.type
' ALLEGRO_JOYSTICK_EVENT-axis alias ALLEGRO_JOYSTICK_EVENT.axis
' ALLEGRO_JOYSTICK_EVENT-timestamp alias ALLEGRO_JOYSTICK_EVENT.timestamp
' ALLEGRO_JOYSTICK_EVENT-pos alias ALLEGRO_JOYSTICK_EVENT.pos
' ALLEGRO_KEYBOARD_EVENT-display alias ALLEGRO_KEYBOARD_EVENT.display
' ALLEGRO_KEYBOARD_EVENT-keycode alias ALLEGRO_KEYBOARD_EVENT.keycode
' ALLEGRO_KEYBOARD_EVENT-source alias ALLEGRO_KEYBOARD_EVENT.source
' ALLEGRO_KEYBOARD_EVENT-modifiers alias ALLEGRO_KEYBOARD_EVENT.modifiers
' ALLEGRO_KEYBOARD_EVENT-type alias ALLEGRO_KEYBOARD_EVENT.type
' ALLEGRO_KEYBOARD_EVENT-unichar alias ALLEGRO_KEYBOARD_EVENT.unichar
' ALLEGRO_KEYBOARD_EVENT-timestamp alias ALLEGRO_KEYBOARD_EVENT.timestamp
' ALLEGRO_KEYBOARD_EVENT-repeat alias ALLEGRO_KEYBOARD_EVENT.repeat
' ALLEGRO_MOUSE_EVENT-w alias ALLEGRO_MOUSE_EVENT.w
' ALLEGRO_MOUSE_EVENT-x alias ALLEGRO_MOUSE_EVENT.x
' ALLEGRO_MOUSE_EVENT-y alias ALLEGRO_MOUSE_EVENT.y
' ALLEGRO_MOUSE_EVENT-z alias ALLEGRO_MOUSE_EVENT.z
' ALLEGRO_MOUSE_EVENT-button alias ALLEGRO_MOUSE_EVENT.button
' ALLEGRO_MOUSE_EVENT-dw alias ALLEGRO_MOUSE_EVENT.dw
' ALLEGRO_MOUSE_EVENT-dx alias ALLEGRO_MOUSE_EVENT.dx
' ALLEGRO_MOUSE_EVENT-dy alias ALLEGRO_MOUSE_EVENT.dy
' ALLEGRO_MOUSE_EVENT-dz alias ALLEGRO_MOUSE_EVENT.dz
' ALLEGRO_MOUSE_EVENT-display alias ALLEGRO_MOUSE_EVENT.display
' ALLEGRO_MOUSE_EVENT-pressure alias ALLEGRO_MOUSE_EVENT.pressure
' ALLEGRO_MOUSE_EVENT-source alias ALLEGRO_MOUSE_EVENT.source
' ALLEGRO_MOUSE_EVENT-type alias ALLEGRO_MOUSE_EVENT.type
' ALLEGRO_MOUSE_EVENT-timestamp alias ALLEGRO_MOUSE_EVENT.timestamp
' ALLEGRO_TIMER_EVENT-source alias ALLEGRO_TIMER_EVENT.source
' ALLEGRO_TIMER_EVENT-count alias ALLEGRO_TIMER_EVENT.count
' ALLEGRO_TIMER_EVENT-error alias ALLEGRO_TIMER_EVENT.error
' ALLEGRO_TIMER_EVENT-type alias ALLEGRO_TIMER_EVENT.type
' ALLEGRO_TIMER_EVENT-timestamp alias ALLEGRO_TIMER_EVENT.timestamp
' ALLEGRO_TOUCH_EVENT-display alias ALLEGRO_TOUCH_EVENT.display
' ALLEGRO_TOUCH_EVENT-primary alias ALLEGRO_TOUCH_EVENT.primary
' ALLEGRO_TOUCH_EVENT-x alias ALLEGRO_TOUCH_EVENT.x
' ALLEGRO_TOUCH_EVENT-source alias ALLEGRO_TOUCH_EVENT.source
' ALLEGRO_TOUCH_EVENT-id alias ALLEGRO_TOUCH_EVENT.id
' ALLEGRO_TOUCH_EVENT-y alias ALLEGRO_TOUCH_EVENT.y
' ALLEGRO_TOUCH_EVENT-dx alias ALLEGRO_TOUCH_EVENT.dx
' ALLEGRO_TOUCH_EVENT-dy alias ALLEGRO_TOUCH_EVENT.dy
' ALLEGRO_TOUCH_EVENT-type alias ALLEGRO_TOUCH_EVENT.type
' ALLEGRO_TOUCH_EVENT-timestamp alias ALLEGRO_TOUCH_EVENT.timestamp
' ALLEGRO_USER_EVENT-__internal__descr alias ALLEGRO_USER_EVENT.__internal__descr
' ALLEGRO_USER_EVENT-data4 alias ALLEGRO_USER_EVENT.data4
' ALLEGRO_USER_EVENT-source alias ALLEGRO_USER_EVENT.source
' ALLEGRO_USER_EVENT-type alias ALLEGRO_USER_EVENT.type
' ALLEGRO_USER_EVENT-data1 alias ALLEGRO_USER_EVENT.data1
' ALLEGRO_USER_EVENT-timestamp alias ALLEGRO_USER_EVENT.timestamp
' ALLEGRO_USER_EVENT-data2 alias ALLEGRO_USER_EVENT.data2
' ALLEGRO_USER_EVENT-data3 alias ALLEGRO_USER_EVENT.data3
' ALLEGRO_EVENT-display alias ALLEGRO_EVENT.display
' ALLEGRO_EVENT-touch alias ALLEGRO_EVENT.touch
' ALLEGRO_EVENT-keyboard alias ALLEGRO_EVENT.keyboard
' ALLEGRO_EVENT-joystick alias ALLEGRO_EVENT.joystick
' ALLEGRO_EVENT-timer alias ALLEGRO_EVENT.timer
' ALLEGRO_EVENT-type alias ALLEGRO_EVENT.type
' ALLEGRO_EVENT-user alias ALLEGRO_EVENT.user
' ALLEGRO_EVENT-mouse alias ALLEGRO_EVENT.mouse
' ALLEGRO_EVENT-any alias ALLEGRO_EVENT.any
' ALLEGRO_FS_ENTRY-vtable alias ALLEGRO_FS_ENTRY.vtable
' ALLEGRO_FS_INTERFACE-fs_open_file alias ALLEGRO_FS_INTERFACE.fs_open_file
' ALLEGRO_FS_INTERFACE-fs_entry_mode alias ALLEGRO_FS_INTERFACE.fs_entry_mode
' ALLEGRO_FS_INTERFACE-fs_remove_entry alias ALLEGRO_FS_INTERFACE.fs_remove_entry
' ALLEGRO_FS_INTERFACE-fs_update_entry alias ALLEGRO_FS_INTERFACE.fs_update_entry
' ALLEGRO_FS_INTERFACE-fs_destroy_entry alias ALLEGRO_FS_INTERFACE.fs_destroy_entry
' ALLEGRO_FS_INTERFACE-fs_create_entry alias ALLEGRO_FS_INTERFACE.fs_create_entry
' ALLEGRO_FS_INTERFACE-fs_entry_name alias ALLEGRO_FS_INTERFACE.fs_entry_name
' ALLEGRO_FS_INTERFACE-fs_entry_exists alias ALLEGRO_FS_INTERFACE.fs_entry_exists
' ALLEGRO_FS_INTERFACE-fs_entry_ctime alias ALLEGRO_FS_INTERFACE.fs_entry_ctime
' ALLEGRO_FS_INTERFACE-fs_entry_size alias ALLEGRO_FS_INTERFACE.fs_entry_size
' ALLEGRO_FS_INTERFACE-fs_filename_exists alias ALLEGRO_FS_INTERFACE.fs_filename_exists
' ALLEGRO_FS_INTERFACE-fs_entry_atime alias ALLEGRO_FS_INTERFACE.fs_entry_atime
' ALLEGRO_FS_INTERFACE-fs_remove_filename alias ALLEGRO_FS_INTERFACE.fs_remove_filename
' ALLEGRO_FS_INTERFACE-fs_entry_mtime alias ALLEGRO_FS_INTERFACE.fs_entry_mtime
' ALLEGRO_FS_INTERFACE-fs_close_directory alias ALLEGRO_FS_INTERFACE.fs_close_directory
' ALLEGRO_FS_INTERFACE-fs_read_directory alias ALLEGRO_FS_INTERFACE.fs_read_directory
' ALLEGRO_FS_INTERFACE-fs_open_directory alias ALLEGRO_FS_INTERFACE.fs_open_directory
' ALLEGRO_FS_INTERFACE-fs_get_current_directory alias ALLEGRO_FS_INTERFACE.fs_get_current_directory
' ALLEGRO_FS_INTERFACE-fs_change_directory alias ALLEGRO_FS_INTERFACE.fs_change_directory
' ALLEGRO_FS_INTERFACE-fs_make_directory alias ALLEGRO_FS_INTERFACE.fs_make_directory
' ALLEGRO_DISPLAY_MODE-refresh_rate alias ALLEGRO_DISPLAY_MODE.refresh_rate
' ALLEGRO_DISPLAY_MODE-height alias ALLEGRO_DISPLAY_MODE.height
' ALLEGRO_DISPLAY_MODE-width alias ALLEGRO_DISPLAY_MODE.width
' ALLEGRO_DISPLAY_MODE-format alias ALLEGRO_DISPLAY_MODE.format
' ALLEGRO_JOYSTICK_STATE-stick alias ALLEGRO_JOYSTICK_STATE.stick
' ALLEGRO_JOYSTICK_STATE-button alias ALLEGRO_JOYSTICK_STATE.button
' ALLEGRO_JOYSTICK_STATE_stick-axis alias ALLEGRO_JOYSTICK_STATE_stick.axis
' ALLEGRO_KEYBOARD_STATE-display alias ALLEGRO_KEYBOARD_STATE.display
' ALLEGRO_KEYBOARD_STATE-__key_down__internal__ alias ALLEGRO_KEYBOARD_STATE.__key_down__internal__
' ALLEGRO_MOUSE_STATE-w alias ALLEGRO_MOUSE_STATE.w
' ALLEGRO_MOUSE_STATE-buttons alias ALLEGRO_MOUSE_STATE.buttons
' ALLEGRO_MOUSE_STATE-display alias ALLEGRO_MOUSE_STATE.display
' ALLEGRO_MOUSE_STATE-x alias ALLEGRO_MOUSE_STATE.x
' ALLEGRO_MOUSE_STATE-more_axes alias ALLEGRO_MOUSE_STATE.more_axes
' ALLEGRO_MOUSE_STATE-y alias ALLEGRO_MOUSE_STATE.y
' ALLEGRO_MOUSE_STATE-z alias ALLEGRO_MOUSE_STATE.z
' ALLEGRO_MOUSE_STATE-pressure alias ALLEGRO_MOUSE_STATE.pressure
' ALLEGRO_TOUCH_STATE-primary alias ALLEGRO_TOUCH_STATE.primary
' ALLEGRO_TOUCH_STATE-display alias ALLEGRO_TOUCH_STATE.display
' ALLEGRO_TOUCH_STATE-x alias ALLEGRO_TOUCH_STATE.x
' ALLEGRO_TOUCH_STATE-id alias ALLEGRO_TOUCH_STATE.id
' ALLEGRO_TOUCH_STATE-y alias ALLEGRO_TOUCH_STATE.y
' ALLEGRO_TOUCH_STATE-dx alias ALLEGRO_TOUCH_STATE.dx
' ALLEGRO_TOUCH_STATE-dy alias ALLEGRO_TOUCH_STATE.dy
' ALLEGRO_TOUCH_INPUT_STATE-touches alias ALLEGRO_TOUCH_INPUT_STATE.touches
' ALLEGRO_MEMORY_INTERFACE-mi_malloc alias ALLEGRO_MEMORY_INTERFACE.mi_malloc
' ALLEGRO_MEMORY_INTERFACE-mi_free alias ALLEGRO_MEMORY_INTERFACE.mi_free
' ALLEGRO_MEMORY_INTERFACE-mi_calloc alias ALLEGRO_MEMORY_INTERFACE.mi_calloc
' ALLEGRO_MEMORY_INTERFACE-mi_realloc alias ALLEGRO_MEMORY_INTERFACE.mi_realloc
' ALLEGRO_MONITOR_INFO-y1 alias ALLEGRO_MONITOR_INFO.y1
' ALLEGRO_MONITOR_INFO-y2 alias ALLEGRO_MONITOR_INFO.y2
' ALLEGRO_MONITOR_INFO-x1 alias ALLEGRO_MONITOR_INFO.x1
' ALLEGRO_MONITOR_INFO-x2 alias ALLEGRO_MONITOR_INFO.x2
' ALLEGRO_TRANSFORM-m alias ALLEGRO_TRANSFORM.m
' ALLEGRO_STATE-_tls alias ALLEGRO_STATE._tls
' ALLEGRO_SAMPLE_ID-_index alias ALLEGRO_SAMPLE_ID._index
' ALLEGRO_SAMPLE_ID-_id alias ALLEGRO_SAMPLE_ID._id
' ALLEGRO_VERTEX_ELEMENT-attribute alias ALLEGRO_VERTEX_ELEMENT.attribute
' ALLEGRO_VERTEX_ELEMENT-storage alias ALLEGRO_VERTEX_ELEMENT.storage
' ALLEGRO_VERTEX_ELEMENT-offset alias ALLEGRO_VERTEX_ELEMENT.offset
' ALLEGRO_VERTEX-color alias ALLEGRO_VERTEX.color
' ALLEGRO_VERTEX-x alias ALLEGRO_VERTEX.x
' ALLEGRO_VERTEX-y alias ALLEGRO_VERTEX.y
' ALLEGRO_VERTEX-z alias ALLEGRO_VERTEX.z
' ALLEGRO_VERTEX-u alias ALLEGRO_VERTEX.u
' ALLEGRO_VERTEX-v alias ALLEGRO_VERTEX.v

\ Misc naming variations
' ALLEGRO_JOYSTICK_STATE.stick alias ALLEGRO_JOYSTICK_STATE.sticks
' ALLEGRO_JOYSTICK_STATE.button alias ALLEGRO_JOYSTICK_STATE.buttons